# Generated by Django 6.0.3 on 2026-03-31 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('tconst', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='IMDb ID')),
                ('title_type', models.CharField(db_index=True, max_length=32, verbose_name='Тип произведения')),
                ('primary_title', models.CharField(db_index=True, max_length=512, verbose_name='Основное название')),
                ('original_title', models.CharField(db_index=True, max_length=512, verbose_name='Оригинальное название')),
                ('is_adult', models.BooleanField(db_index=True, default=False, verbose_name='18+')),
                ('start_year', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Год начала')),
                ('end_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год окончания')),
                ('runtime_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность (мин.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('genres', models.ManyToManyField(blank=True, related_name='titles', to='main.genre', verbose_name='Жанры')),
            ],
            options={
                'verbose_name': 'Произведение',
                'verbose_name_plural': 'Произведения',
                'ordering': ['-start_year', 'primary_title'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('nconst', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='IMDb ID')),
                ('primary_name', models.CharField(db_index=True, max_length=255, verbose_name='Имя')),
                ('birth_year', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Год рождения')),
                ('death_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год смерти')),
                ('primary_professions', models.JSONField(blank=True, default=list, verbose_name='Профессии')),
                ('known_for_titles', models.ManyToManyField(blank=True, related_name='known_for_people', to='main.title', verbose_name='Известен по произведениям')),
            ],
            options={
                'verbose_name': 'Персона',
                'verbose_name_plural': 'Персоны',
                'ordering': ['primary_name'],
            },
        ),
        migrations.CreateModel(
            name='TitleCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('director', 'Режиссер'), ('writer', 'Сценарист')], db_index=True, max_length=16, verbose_name='Роль')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_titles', to='main.person', verbose_name='Персона')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_members', to='main.title', verbose_name='Произведение')),
            ],
            options={
                'verbose_name': 'Участник съемочной группы',
                'verbose_name_plural': 'Участники съемочной группы',
            },
        ),
        migrations.CreateModel(
            name='TitlePrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(verbose_name='Порядок')),
                ('category', models.CharField(db_index=True, max_length=64, verbose_name='Категория')),
                ('job', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность')),
                ('characters', models.JSONField(blank=True, null=True, verbose_name='Персонажи')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='principal_titles', to='main.person', verbose_name='Персона')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='principals', to='main.title', verbose_name='Произведение')),
            ],
            options={
                'verbose_name': 'Основной участник',
                'verbose_name_plural': 'Основные участники',
                'ordering': ['title', 'ordering'],
            },
        ),
        migrations.CreateModel(
            name='TitleRating',
            fields=[
                ('title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='rating', serialize=False, to='main.title', verbose_name='Произведение')),
                ('average_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Средний рейтинг')),
                ('num_votes', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Количество голосов')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
                'ordering': ['-average_rating', '-num_votes'],
                'indexes': [models.Index(fields=['average_rating', 'num_votes'], name='main_titler_average_8e758a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='title',
            index=models.Index(fields=['title_type', 'start_year'], name='main_title_title_t_5d52e7_idx'),
        ),
        migrations.AddIndex(
            model_name='title',
            index=models.Index(fields=['primary_title'], name='main_title_primary_7b80ae_idx'),
        ),
        migrations.AddIndex(
            model_name='title',
            index=models.Index(fields=['original_title'], name='main_title_origina_556c8e_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['primary_name'], name='main_person_primary_db437f_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['birth_year'], name='main_person_birth_y_da40f3_idx'),
        ),
        migrations.AddIndex(
            model_name='titlecrew',
            index=models.Index(fields=['title', 'role'], name='main_titlec_title_i_0c8142_idx'),
        ),
        migrations.AddIndex(
            model_name='titlecrew',
            index=models.Index(fields=['person', 'role'], name='main_titlec_person__1b46b6_idx'),
        ),
        migrations.AddConstraint(
            model_name='titlecrew',
            constraint=models.UniqueConstraint(fields=('title', 'person', 'role'), name='unique_title_person_role'),
        ),
        migrations.AddIndex(
            model_name='titleprincipal',
            index=models.Index(fields=['title', 'ordering'], name='main_titlep_title_i_96bc9f_idx'),
        ),
        migrations.AddIndex(
            model_name='titleprincipal',
            index=models.Index(fields=['person', 'category'], name='main_titlep_person__8b7786_idx'),
        ),
        migrations.AddIndex(
            model_name='titleprincipal',
            index=models.Index(fields=['category'], name='main_titlep_categor_cdb51b_idx'),
        ),
        migrations.AddConstraint(
            model_name='titleprincipal',
            constraint=models.UniqueConstraint(fields=('title', 'ordering'), name='unique_principal_ordering_per_title'),
        ),
        migrations.AddConstraint(
            model_name='titleprincipal',
            constraint=models.UniqueConstraint(fields=('title', 'person', 'category', 'ordering'), name='unique_title_person_category_ordering'),
        ),
    ]
