# Generated by Django 6.0.3 on 2026-04-05 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nconst', models.CharField(max_length=16, unique=True, verbose_name='IMDb ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('birth_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год рождения')),
                ('death_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год смерти')),
                ('primary_professions', models.TextField(blank=True, null=True, verbose_name='Профессии')),
            ],
            options={
                'verbose_name': 'Персона',
                'verbose_name_plural': 'Персоны',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tconst', models.CharField(max_length=16, unique=True, verbose_name='IMDb ID')),
                ('title_type', models.PositiveSmallIntegerField(choices=[(1, 'Фильм'), (2, 'Короткометражка'), (3, 'Сериал'), (4, 'Мини-сериал'), (5, 'ТВ-фильм'), (6, 'Эпизод'), (7, 'ТВ-короткометражка'), (8, 'ТВ-спецвыпуск'), (9, 'ТВ-пилот'), (10, 'Видео'), (11, 'Видеоигра'), (12, 'Подкаст-сериал'), (13, 'Эпизод подкаста'), (14, 'Радиосериал'), (15, 'Радиоэпизод'), (16, 'Музыкальное видео'), (17, 'Аудиокнига'), (99, 'Другое')], verbose_name='Тип произведения')),
                ('title', models.CharField(max_length=512, verbose_name='Основное название')),
                ('is_adult', models.BooleanField(default=False, verbose_name='18+')),
                ('start_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год начала')),
                ('end_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год окончания')),
                ('runtime_minutes', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Длительность (мин.)')),
                ('genres', models.ManyToManyField(blank=True, related_name='titles', to='main.genre', verbose_name='Жанры')),
            ],
            options={
                'verbose_name': 'Произведение',
                'verbose_name_plural': 'Произведения',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='rating', serialize=False, to='main.title', verbose_name='Произведение')),
                ('average_rating_tenths', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Средний рейтинг x10')),
                ('num_votes', models.PositiveIntegerField(default=0, verbose_name='Количество голосов')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
            },
        ),
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(verbose_name='Порядок')),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'Актер'), (2, 'Актриса'), (3, 'Режиссер'), (4, 'Сценарист'), (5, 'Продюсер'), (6, 'Композитор'), (7, 'Монтажер'), (8, 'Оператор'), (9, 'Играет себя'), (10, 'Архивные кадры'), (11, 'Архивный звук'), (12, 'Саундтрек'), (13, 'Помощник режиссера'), (14, 'Кастинг-директор'), (15, 'Художник-постановщик'), (16, 'Арт-директор'), (17, 'Художник по костюмам'), (18, 'Грим'), (19, 'Камерный отдел'), (20, 'Музыкальный отдел'), (21, 'Звуковой отдел'), (22, 'Визуальные эффекты'), (23, 'Анимационный отдел'), (24, 'Исполнительный продюсер'), (25, 'Архивный материал'), (99, 'Другое')], verbose_name='Категория')),
                ('job', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность')),
                ('characters', models.TextField(blank=True, null=True, verbose_name='Персонажи')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='principal_titles', to='main.person', verbose_name='Персона')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='principals', to='main.title', verbose_name='Произведение')),
            ],
            options={
                'verbose_name': 'Основной участник',
                'verbose_name_plural': 'Основные участники',
                'constraints': [models.UniqueConstraint(fields=('title', 'ordering'), name='unique_principal_ordering_per_title'), models.UniqueConstraint(fields=('title', 'person', 'category', 'ordering'), name='unique_title_person_category_ordering')],
            },
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'Режиссер'), (2, 'Сценарист')], verbose_name='Роль')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_titles', to='main.person', verbose_name='Персона')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_members', to='main.title', verbose_name='Произведение')),
            ],
            options={
                'verbose_name': 'Участник съемочной группы',
                'verbose_name_plural': 'Участники съемочной группы',
                'constraints': [models.UniqueConstraint(fields=('title', 'person', 'role'), name='unique_title_person_role')],
            },
        ),
    ]
