# Generated by Django 6.0.3 on 2026-04-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='runtime_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность (мин.)'),
        ),
    ]
