# Generated by Django 6.0.3 on 2026-03-31 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='person',
            name='main_person_primary_db437f_idx',
        ),
        migrations.RemoveIndex(
            model_name='person',
            name='main_person_birth_y_da40f3_idx',
        ),
        migrations.RemoveIndex(
            model_name='title',
            name='main_title_title_t_5d52e7_idx',
        ),
        migrations.RemoveIndex(
            model_name='title',
            name='main_title_primary_7b80ae_idx',
        ),
        migrations.RemoveIndex(
            model_name='title',
            name='main_title_origina_556c8e_idx',
        ),
        migrations.RemoveIndex(
            model_name='titlecrew',
            name='main_titlec_title_i_0c8142_idx',
        ),
        migrations.RemoveIndex(
            model_name='titlecrew',
            name='main_titlec_person__1b46b6_idx',
        ),
        migrations.RemoveIndex(
            model_name='titleprincipal',
            name='main_titlep_title_i_96bc9f_idx',
        ),
        migrations.RemoveIndex(
            model_name='titleprincipal',
            name='main_titlep_person__8b7786_idx',
        ),
        migrations.RemoveIndex(
            model_name='titleprincipal',
            name='main_titlep_categor_cdb51b_idx',
        ),
        migrations.RemoveIndex(
            model_name='titlerating',
            name='main_titler_average_8e758a_idx',
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Год рождения'),
        ),
        migrations.AlterField(
            model_name='person',
            name='primary_name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='title',
            name='is_adult',
            field=models.BooleanField(default=False, verbose_name='18+'),
        ),
        migrations.AlterField(
            model_name='title',
            name='original_title',
            field=models.CharField(max_length=512, verbose_name='Оригинальное название'),
        ),
        migrations.AlterField(
            model_name='title',
            name='primary_title',
            field=models.CharField(max_length=512, verbose_name='Основное название'),
        ),
        migrations.AlterField(
            model_name='title',
            name='start_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Год начала'),
        ),
        migrations.AlterField(
            model_name='title',
            name='title_type',
            field=models.CharField(max_length=32, verbose_name='Тип произведения'),
        ),
        migrations.AlterField(
            model_name='titlecrew',
            name='role',
            field=models.CharField(choices=[('director', 'Режиссер'), ('writer', 'Сценарист')], max_length=16, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='titleprincipal',
            name='category',
            field=models.CharField(max_length=64, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='titlerating',
            name='num_votes',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество голосов'),
        ),
    ]
