# Generated by Django 6.0.3 on 2026-04-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_person_main_person_primary_db437f_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='original_title',
            field=models.CharField(max_length=512, null=True, verbose_name='Оригинальное название'),
        ),
    ]
