# Generated by Django 6.0.3 on 2026-04-01 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_title_original_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='original_title',
        ),
    ]
