# Generated by Django 6.0.3 on 2026-04-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_title_original_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='end_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год окончания'),
        ),
        migrations.AlterField(
            model_name='title',
            name='start_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год начала'),
        ),
    ]
