# Generated by Django 6.0.3 on 2026-04-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_title_end_year_alter_title_start_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Персона', 'verbose_name_plural': 'Персоны'},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name': 'Произведение', 'verbose_name_plural': 'Произведения'},
        ),
        migrations.AlterModelOptions(
            name='titleprincipal',
            options={'verbose_name': 'Основной участник', 'verbose_name_plural': 'Основные участники'},
        ),
        migrations.AlterModelOptions(
            name='titlerating',
            options={'verbose_name': 'Рейтинг', 'verbose_name_plural': 'Рейтинги'},
        ),
        migrations.RemoveField(
            model_name='person',
            name='known_for_titles',
        ),
        migrations.AddField(
            model_name='person',
            name='primary_professions_text',
            field=models.TextField(blank=True, null=True, verbose_name='Профессии'),
        ),
        migrations.AddField(
            model_name='title',
            name='title_type_code',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Фильм'), (2, 'Короткометражка'), (3, 'Сериал'), (4, 'Мини-сериал'), (5, 'ТВ-фильм'), (6, 'Эпизод'), (7, 'ТВ-короткометражка'), (8, 'ТВ-спецвыпуск'), (9, 'ТВ-пилот'), (10, 'Видео'), (11, 'Видеоигра'), (12, 'Подкаст-сериал'), (13, 'Эпизод подкаста'), (14, 'Радиосериал'), (15, 'Радиоэпизод'), (16, 'Музыкальное видео'), (17, 'Аудиокнига'), (99, 'Другое')], null=True, verbose_name='Тип произведения'),
        ),
        migrations.AddField(
            model_name='titlecrew',
            name='role_code',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Режиссер'), (2, 'Сценарист'), (99, 'Другое')], null=True, verbose_name='Роль'),
        ),
        migrations.AddField(
            model_name='titleprincipal',
            name='category_code',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Актер'), (2, 'Актриса'), (3, 'Режиссер'), (4, 'Сценарист'), (5, 'Продюсер'), (6, 'Композитор'), (7, 'Монтажер'), (8, 'Оператор'), (9, 'Играет себя'), (10, 'Архивные кадры'), (11, 'Архивный звук'), (12, 'Саундтрек'), (13, 'Помощник режиссера'), (14, 'Кастинг-директор'), (15, 'Художник-постановщик'), (16, 'Арт-директор'), (17, 'Художник по костюмам'), (18, 'Грим'), (19, 'Камерный отдел'), (20, 'Музыкальный отдел'), (21, 'Звуковой отдел'), (22, 'Визуальные эффекты'), (23, 'Анимационный отдел'), (24, 'Исполнительный продюсер'), (99, 'Другое')], null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='titleprincipal',
            name='characters_text',
            field=models.TextField(blank=True, null=True, verbose_name='Персонажи'),
        ),
        migrations.AlterField(
            model_name='person',
            name='primary_professions',
            field=models.JSONField(blank=True, default=list, verbose_name='Профессии (старый формат)'),
        ),
        migrations.AlterField(
            model_name='title',
            name='title_type',
            field=models.CharField(max_length=32, verbose_name='Тип произведения (старый формат)'),
        ),
        migrations.AlterField(
            model_name='titlecrew',
            name='role',
            field=models.CharField(max_length=16, verbose_name='Роль (старый формат)'),
        ),
        migrations.AlterField(
            model_name='titleprincipal',
            name='category',
            field=models.CharField(max_length=64, verbose_name='Категория (старый формат)'),
        ),
        migrations.AlterField(
            model_name='titleprincipal',
            name='characters',
            field=models.JSONField(blank=True, null=True, verbose_name='Персонажи (старый формат)'),
        ),
    ]
