# Generated by Django 6.0.3 on 2026-04-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_genre_options_alter_person_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='primary_professions_text',
        ),
        migrations.RemoveField(
            model_name='title',
            name='title_type_code',
        ),
        migrations.RemoveField(
            model_name='titlecrew',
            name='role_code',
        ),
        migrations.RemoveField(
            model_name='titleprincipal',
            name='category_code',
        ),
        migrations.RemoveField(
            model_name='titleprincipal',
            name='characters_text',
        ),
        migrations.AlterField(
            model_name='person',
            name='primary_professions',
            field=models.JSONField(blank=True, default=list, verbose_name='Профессии'),
        ),
        migrations.AlterField(
            model_name='title',
            name='title_type',
            field=models.CharField(max_length=32, verbose_name='Тип произведения'),
        ),
        migrations.AlterField(
            model_name='titlecrew',
            name='role',
            field=models.CharField(choices=[('director', 'Режиссер'), ('writer', 'Сценарист')], max_length=16, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='titleprincipal',
            name='category',
            field=models.CharField(max_length=64, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='titleprincipal',
            name='characters',
            field=models.JSONField(blank=True, null=True, verbose_name='Персонажи'),
        ),
    ]
