# Generated by Django 6.0.3 on 2026-04-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_person_primary_professions_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=16, unique=True, verbose_name='Название'),
        ),
    ]
