# Generated by Django 6.0.3 on 2026-04-05 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_title_created_at_alter_genre_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='primary_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='title',
            old_name='primary_title',
            new_name='title',
        ),
    ]
