# Generated by Django 6.0.3 on 2026-04-05 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_primary_name_person_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TitleCrew',
            new_name='Crew',
        ),
        migrations.RenameModel(
            old_name='TitlePrincipal',
            new_name='Principal',
        ),
        migrations.RenameModel(
            old_name='TitleRating',
            new_name='Rating',
        ),
    ]
