# Generated by Django 6.0.3 on 2026-04-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_titlecrew_crew_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год рождения'),
        ),
        migrations.AlterField(
            model_name='person',
            name='death_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год смерти'),
        ),
    ]
