# Generated by Django 6.0.3 on 2026-04-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_person_birth_year_alter_person_death_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='runtime_minutes',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Длительность (мин.)'),
        ),
    ]
